#ifndef __EVENTIDS__
#define __EVENTIDS__

enum GBEVENT_ID
{
    GBEVENT_NETWORK,
    GBEVENT_NETWORK_LOGIN,
    GBEVENT_NETWORK_ROOM,
	GBEVENT_NETWORK_GAME,
    //GBEVENT_READ,
    
    GBEVENT_UI_LOGINFINISH,              //登陆完成
    //GBEVENT_UI_ANS_LOGINFINISH,        //匿名登陆完成
    GBEVENT_UI_LOGINFAILE,               //登陆失败
    
    GBEVENT_UI_ROOMLOGINFINISH,          //房间登陆完成
    GBEVENT_UI_REGISTERFAILE,            //注册失败
    GBEVENT_UI_REGISTERSUCC,             //注册成功
    
    //GBEVENT_UI_FIMDPASSWORD,             //密码找回
    GBEVENT_UI_GAMEMESSAGE,         //游戏消息
    GBEVENT_UI_SCENEMESSAGE,        //场景消息
    
    GBEVENT_UI_SYSTEM,              //系统消息
};

//#define  MSG_ANS_NETWORK		  "MSG_ANS_NETWORK"				//网络消息
#define MSG_UI_ANS_ROOMLOGINFAIL  "MSG_UI_ANS_ROOMLOGINFAIL"     //房间登录失败
#define MSG_UI_ANS_SITFAIL        "MSG_UI_ANS_SITFAIL"           //坐下失败
#define MSG_UI_ANS_LOGINFINISH    "MSG_UI_ANS_LOGINFINISH"
#define MSG_UI_ANS_LOGINFAIL      "MSG_UI_ANS_LOGINFAIL"
#define MSG_UI_ANS_REGNFAIL       "MSG_UI_ANS_REGNFAIL"			 //注册失败
#define MSG_UI_ANS_REGSUCC        "MSG_UI_ANS_REGSUCC"			 //注册成功
#define MSG_UI_ANS_CANCELAUTO     "MSG_UI_ANS_CANCELAUTO"        //取消托管
#define MSG_UI_ANS_DISCARD        "MSG_UI_ANS_DISCARD"           //开始发牌
#define MSG_UI_ANS_FINDPASS       "MSG_UI_ANS_FINDPASS"          //密码找回
#define MSG_UI_ANS_MATCH          "MSG_UI_ANS_MATCH"             //匹配玩家
#define MSG_UI_ANS_MATCHDZPK          "MSG_UI_ANS_MATCHDZPK"             //匹配玩家DZPK
#define MSG_UI_ANS_PRESENT        "MSG_UI_ANS_PRESENT"           //金币赠送
#define MSG_UI_ANS_CHARGE         "MSG_UI_ANS_CHARGE"            //领取金币发费
#define MSG_UI_ANS_BANKRUPT       "MSG_UI_ANS_BANKRUPT"          //破产信息
#define MSG_UI_ANS_USERLIST       "MSG_UI_ANS_USERLIST"          //用户列表
#define MSG_UI_ANS_USERSEND       "MSG_UI_ANS_USERSEND"          //用户发送
#define MSG_UI_ANS_CHARGETIPS     "MSG_UI_ANS_CHARGETIPS"        //充值提示
#define MSG_UI_ANS_CLOSEDOWM      "MSG_UI_ANS_CLOSEDOWM"         //关闭消息
#define MSG_UI_ANS_CHARGEFINISH   "MSG_UI_ANS_CHARGEFINISH"      //充值完成
#define MSG_UI_ANS_EXPRESSION     "MSG_UI_ANS_EXPRESSION"        //表情消息
#define MSG_UI_ANS_NETWORKSHUT    "MSG_UI_ANS_NETWORKSHUT"       //网络断开
#define MSG_UI_ANS_NETWORKSHUTDZPK    "MSG_UI_ANS_NETWORKSHUTDZPK"       //网络断开DZPK
#define MSG_UI_ANS_NETWORK_RECON	"MSG_UI_ANS_NETWORK_RECON"		//网络重连
#define MSG_UI_ANS_NETWORK_RECONDZPK "MSG_UI_ANS_NETWORK_RECONDZPK"	//网络重连dzpk
#define MSG_UI_ANS_NETWORK_RECON_ING "MSG_UI_ANS_NETWORK_RECON_ING"//网络重连中
#define MSG_UI_ANS_VERUPDATE      "MSG_UI_ANS_VERUPDATE"         //版本更新
#define MSG_UI_ANS_LEVELUP        "MSG_UI_ANS_LEVELUP"           //升级
#define MSG_UI_ANS_HIDEFACEUI     "MSG_UI_ANS_HIDEFACEUI"        //隐藏表情界面
#define MSG_UI_ANS_PLAYERUPDATE   "MSG_UI_ANS_PLAYERUPDATE"      //人物信息
#define MSG_UI_ANS_PLAYERUPDATEDZPK   "MSG_UI_ANS_PLAYERUPDATEDZPK"      //德州扑克人物信息
#define GBEVENT_UI_SYSTEM         "GBEVENT_UI_SYSTEM"            //系统消息
#define GBEVENT_UI_GAMEMESSAGE    "GBEVENT_UI_GAMEMESSAGE"       //游戏消息
#define GBEVENT_UI_GAMEMESSAGEDZPK    "GBEVENT_UI_GAMEMESSAGEDZPK"       //德州扑克游戏消息
#define GBEVENT_UI_SCENEMESSAGEDZPK   "GBEVENT_UI_SCENEMESSAGEDZPK"      //德州扑克游戏场景消息
#define GBEVENT_UI_SCENEMESSAGE   "GBEVENT_UI_SCENEMESSAGE"      //游戏场景消息
#define MSG_UI_ANS_CLICKTIPS	  "MSG_UI_ANS_CLICKTIPS"		 //游戏图标点击消息
#define MSG_UI_ANS_NICKNAMEUPDATE "MSG_UI_ANS_NICKNAMEUPDATE"	 //昵称修改成功
#define MSG_UI_ANS_PASSWORDUPDATE "MSG_UI_ANS_PASSWORDUPDATE"	 //密码修改成功
#define MSG_UI_ANS_TOUXIANGUPDATE "MSG_UI_ANS_TOUXIANGUPDATE"	 //头像修改成功
#define MSG_UI_ANS_VERSIONERROR	"MSG_UI_ANS_VERSIONERROR"		//版本信息
#define MSG_UI_ANS_UPDATETOUXIANGNUM	"MSG_UI_ANS_UPDATETOUXIANGNUM"		//头像修改参数
#define MSG_UI_ANS_UPDATETOUXIANGLAYER	"MSG_UI_ANS_UPDATETOUXIANGLAYER"		//删除头像层
#define MSG_UI_ANS_UPDATASEVERSHUT	"MSG_UI_ANS_UPDATASEVERSHUT"		//服务器断开
#define MSG_UI_ANS_SUREMODYFINICKNAME	"MSG_UI_ANS_SUREMODYFINICKNAME"		//确定修改昵称
#define MSG_UI_ANS_GETAWARDRESULT	"MSG_UI_ANS_GETAWARDRESULT"		//获得邓丽奖励结果
#define MSG_UI_ANS_UPDATESCOREANDGOLDEGG	"MSG_UI_ANS_UPDATESCOREANDGOLDEGG"		//刷新钱和话费点
#define MSG_UI_ANS_LANDCARDRESULT	"MSG_UI_ANS_LANDCARDRESULT"		//紫金岛卡充值结果
#define MSG_UI_ANS_PHONECARDRESULT	"MSG_UI_ANS_PHONECARDRESULT"		//充值卡充值结果
#define MSG_UI_ANS_DOWNLOADPESENT	"MSG_UI_ANS_DOWNLOADPESENT"		//后台下载进度
#define MSG_UI_ANS_FREELIST	"MSG_UI_ANS_FREELIST"		//免费中游戏下载的情况
#define MSG_UI_ANS_TASKGETSUCC	"MSG_UI_ANS_TASKGETSUCC"		//任务领取成功
#define MSG_UI_ANS_TASKGETFAIL	"MSG_UI_ANS_TASKGETFAIL"		//任务领取失败
#define MSG_UI_ANS_REFRESHTOTALNUM "MSG_UI_ANS_REFRESHTOTALNUM"	//在线人数
#define MSG_UI_ANS_DOWNLOADDATA "MSG_UI_ANS_DOWNLOADDATA"	//下载返回数据
#define MSG_UI_ANS_DOWNLOADAWARDOVER "MSG_UI_ANS_DOWNLOADAWARDOVER"	//获取下载奖励完成

#define MSG_UI_ANS_CHANGSHAMAJIADOWNLOAD	"MSG_UI_ANS_CHANGSHAMAJIADOWNLOAD"		//长沙麻将下载
#define MSG_UI_ANS_RUNFASTDOWNLOAD	"MSG_UI_ANS_RUNFASTDOWNLOAD"		//跑得快下载
#define MSG_UI_ANS_THREETOONE	"MSG_UI_ANS_THREETOONE"		//三打哈下载
#define MSG_UI_ANS_RUNBREAD	"MSG_UI_ANS_RUNBREAD"		//跑胡子下载
#define MSG_UI_ANS_CANNELDOWNLOADGAME "MSG_UI_ANS_CANNELDOWNLOADGAME"
#define MSG_UI_ANS_OVERREGISTRES "MSG_UI_ANS_OVERREGISTRES" //完善注册返回
#define MSG_UI_ANS_GAMELINK "MSG_UI_ANS_GAMELINK" //游戏连接返回
#define MSG_UI_ANS_CANNELRECHANGER "MSG_UI_ANS_CANNELRECHANGER" //破产取消充值
#define MSG_UI_ANS_GETSAVECOINS "MSG_UI_ANS_GETSAVECOINS"//领取救济金成功
#define MSG_UI_ANS_VERSIONNEW "MSG_UI_ANS_VERSIONNEW"//当前版本为最新
#define MSG_UI_ANS_INVITE "MSG_UI_ANS_INVITE"//好友邀请

#define MSG_UI_ANS_GBEVENT_UI_ROOMLOGINFINISH "MSG_UI_ANS_GBEVENT_UI_ROOMLOGINFINISH"  //进入登陆房间
#define MSG_UI_ANSLoginConnectFaild "MSG_UI_ANSLoginConnectFaild"
#define MSG_UI_ANSLoginOtherSFaild "MSG_UI_ANSLoginOtherSFaild"
#define REGISTRATIONLAYERGAMETOBUY  "REGISTRATIONLAYERGAMETOBUY"  //重新买入

#endif